---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: metabase-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  hostPath:
    path: /tmp/metabase-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 10Gi